### ISSUE TITLE
Redis cluster client crashes for commands when no keys are passed

### ISSUE THREAD

**Issue by GumpacG** [amazon-contributing/redis-rs#158]
**Describe the bug**
The Redis cluster client crashes for the java client when commands that expect an array of keys are passed in an empty array.

**To Reproduce**
1. Start the java client with [RedisClusterClient](https://github.com/aws/glide-for-redis/blob/main/java/client/src/main/java/glide/api/RedisClusterClient.java).
```
clusterClient =
                RedisClusterClient.CreateClient(
                                RedisClusterClientConfiguration.builder()
                                        .address(NodeAddress.builder().port(TestConfiguration.CLUSTER_PORTS[0]).build())
                                        .requestTimeout(5000)
                                        .build())
                        .get();
```
3. Run `clusterClient.del(new String[0]).get()`
```
thread '<unnamed>' panicked at /Users/user/Documents/ElastiCache/GitHub/glide-for-redis/submodules/redis-rs/redis/src/cluster_async/mod.rs:860:54:
[2m2024-06-14T00:25:32.893664Z[0m [33m WARN[0m [2mlogger_core[0m[2m:[0m received error - Received connection error `redis_cluster: Unable to receive command`. Will attempt to reconnect
called `Option::unwrap()` on a `None` value
```
![Screenshot 2024-06-13 at 5 36 37 PM](https://github.com/amazon-contributing/redis-rs/assets/29149268/52e2eeb1-1398-469c-b554-43b5aa5d24d6)

**Expected behavior**
An exception error similar to the exception that a standalone client would throw like:
```
127.0.0.1:6379> DEL
(error) ERR wrong number of arguments for 'del' command` 
```

**Comment by barshaul** [comment]
Fixed
